version: "3.8"

services:
  web:
    depends_on: 
      - api
    build: ./client
    ports:
      - 3000:3000
    environment:
      REACT_APP_PUBLIC_FOLDER: https://connectrbackend.onrender.com/images/
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync

  api: 
    build: ./server
    ports: 
      - 8800:8800
    environment: 
      MONGO_URL: mongodb+srv://admin:admin123@cluster0.mtpyogh.mongodb.net/myDB
    
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        
        - path: ./server
          target: /app
          action: sync

volumes:
  socials: